### ISSUE TITLE
:lady_beetle: [BUG] App crashes when deleting scheduled message

### ISSUE THREAD

**Issue by octoshrimpy** [octoshrimpy/quik#15]
### DESCRIPTION
App crashes when trying to delete scheduled message. Running graphene os

### STEPS
1. Schedule message to send
2. Go to schedule messages screen
3. Click on message and tap delete

### OBSERVATIONS
```
type: crash
osVersion: google/cheetah/cheetah:13/TQ1A.230105.002/2023011000:user/release-keys
package: com.moez.QKSMS:2220
process: com.moez.QKSMS
processUptime: 7741 + 276 ms

io.reactivex.exceptions.OnErrorNotImplementedException: Running transactions on the UI thread has been disabled. It can be enabled by setting 'RealmConfiguration.Builder.allowWritesOnUiThread(true)'.
Caused by: io.realm.exceptions.RealmException: Running transactions on the UI thread has been disabled. It can be enabled by setting 'RealmConfiguration.Builder.allowWritesOnUiThread(true)'.
	at com.moez.QKSMS.feature.scheduled.ScheduledViewModel.bindView(ScheduledViewModel.kt:71)
	at [[ ↑↑ Inferred subscribe point ↑↑ ]].(:0)
	at [[ ↓↓ Original trace ↓↓ ]].(:0)
	at io.realm.BaseRealm.checkAllowWritesOnUiThread(BaseRealm.java:553)
	at io.realm.Realm.executeTransaction(Realm.java:1629)
	at com.moez.QKSMS.repository.ScheduledMessageRepositoryImpl.deleteScheduledMessage(ScheduledMessageRepositoryImpl.kt:72)
	at com.moez.QKSMS.feature.scheduled.ScheduledViewModel$bindView$$inlined$withLatestFrom$1.apply(Observables.kt:198)
	at io.reactivex.internal.operators.observable.ObservableWithLatestFrom$WithLatestFromObserver.onNext(ObservableWithLatestFrom.java:76)
	at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
	at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
	at com.moez.QKSMS.common.MenuItemAdapter.onCreateViewHolder$lambda$8$lambda$7(MenuItemAdapter.kt:80)
	at com.moez.QKSMS.common.MenuItemAdapter.$r8$lambda$RH34JQv66UoAa-rn53rPXw-lQMY(Unknown Source:0)
	at com.moez.QKSMS.common.MenuItemAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7506)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29341)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)```

```

---

https://github.com/moezbhatti/qksms/issues/1911

**Comment by octoshrimpy** [comment]
fixed.

**Comment by joseio** [comment]
In QKSMS get 3.10.1 this issue persists for me on grapheneos, unfortunately
