### ISSUE TITLE
:lady_beetle: [BUG] Messages sending problem 

### ISSUE THREAD

**Issue by qmnb12** [octoshrimpy/quik#616]
**I am unable to send messages to contacts in my contact list**
Whenever I try to message a contact, whether I do it directly in the app or through the dialer or contacts, I don't see any option to type or send a message. 

**To Reproduce**
1. Go to '+'
2. Click on 'Contact'
3. See Problem 

**Expected behavior**
Only the reload symbol keeps rotating. 

**Smartphone (please complete the following information):**
 - Device: [Redmi 12 5G]
 - OS: [Android 15 , Hyper OS 2.0.2]
 - App Version [e.g. 4.3.2]

**Screenshots**

![Image](https://github.com/user-attachments/assets/d7f4e6e9-5e31-4f10-b132-8c63f4fd3029)

**Additional context**
This happens whenever I try to send a message to any contact from Contacts & Dialer and also when I do it by opening the app.

Please solve this quickly. If we cannot send messages from the Messages app, then the app becomes useless.

Please give an update immediately.

**Comment by Inhishonor** [comment]
@qmnb12 I am unable to reproduce this issue. Can you please clear cache and see if the issue persists. If it does, can you collect logs. Instructions can be found here: https://github.com/octoshrimpy/quik/wiki/Frequently-Asked-Questions#Troubleshooting

Is it only a specific contact? Just confirming you are running 4.3.2?

**Comment by qmnb12** [comment]
FIRST I OPEN APP AND CLICK + SYMBOL

![Image](https://github.com/user-attachments/assets/cd59ba43-8430-4864-b0c3-0cba855397b2)

THEN SELECT ANY CONTACT

![Image](https://github.com/user-attachments/assets/22a4e9b2-a890-4f07-83f9-6f2e0eb0f1ea)

AFTER THAT SHOWING THIS... I AM UPLOADING VIDEO

https://github.com/user-attachments/assets/7974f5ed-cefb-4379-ba94-60ca4d7aca8c

SAME WHEN I OPEN VIA PHONE CONTACTS AND DIALER APP EXAMPLE SS... 

![Image](https://github.com/user-attachments/assets/af697fb9-84ea-4f75-ba67-11271cbd48bb)

You understand or you need anything 

YES SHOWING IN ALL CONTACTS AND YES I AM USING THE LATEST VERSION OF APP 4.3.2...

**Comment by qmnb12** [comment]
[quiklogcat.txt](https://github.com/user-attachments/files/24103387/quiklogcat.txt)

Anything Else..?

**Comment by qmnb12** [comment]
You find anything or not please reply..?

**Comment by Inhishonor** [comment]
@qmnb12 Unfortunately, this doesn't appear to be an issue with QUIK itself, though to verify, can you do the following?
- Install https://github.com/octoshrimpy/quik/releases/download/v4.3.1/QUIK-v4.3.1-release.apk and see if the issue is still there. This will require you to uninstall the app and then reinstall it.
- Verify that every single possible permission is granted to QUIK.

Also, have you had any system updates in the meantime? 
Did 4.1.1 or 4.1.0 work in the past? 
Do you have anything like pocket mode or something similar turned on in the OS?

In all honesty, I have absolutely no clue what is causing this. The only idea I have is that the either a system crash is interrupting something, or the contact is not being returned by your OS properly and QUIK lost it's ability to handle that.

**Comment by theamazing0** [comment]
Same issue but rather than being stuck on loading it just fails to load and either returns to the main page or starts "not responding".

I'm on a Google Pixel 9a running GrapheneOS with version 4.3.1. Attaching the logs that it prompts to view when it says "not responding".

[Error in QUIK 602d4140d1ac.txt](https://github.com/user-attachments/files/24118544/Error.in.QUIK.602d4140d1ac.txt)

**Comment by theamazing0** [comment]
I updated to 4.3.2 and it appears to be fixed.

**Comment by qmnb12** [comment]
Ok Reinstall 4.3.2 its not working 

Then install 4.3.1 its not working but sending or msg typing interface showing 0.1 second.. i only feel again and again.. 

Then i install 4.1.1 its working fine without any problem... But this appears when you open the message from the contact or dialer.

![Image](https://github.com/user-attachments/assets/1c9d5c0e-eb23-42c4-98c6-8dc5da26d537)

2nd Question Ans = Yes, I have given all the permissions to the app.

3rd Que Ans = My mobile system is up to date । No Pending updates 

4th Que Ans = No Pocket mode enabled

**Comment by kyrzzz** [comment]
Interestingly, the same behaviour is present on my POCO F8 Pro device running HyperOS 3.0.6.0 on top of Android 16 tested on 4.3.2 of QUIK.

But even the 4.1.1 version refuses to work though, I cant send any messages as it always brings me back to the previous screen in the app.

Notifications, Restricted Permissions were all granted, battery optimization is off as well. Maybe its an issue with HyperOS (as usual)? Im not sure if turning off HyperOS Optimizations within Developer Mode will help, but Im reluctant to do it because my past experiences, it reset a lot of my settings for all my apps. Hopefully someone else can try too

**Comment by qmnb12** [comment]
Please solve this problem...

**Comment by Inhishonor** [comment]
Please be patient. I am working on this issue, but as you can see from the issue tracker there are many regressions. In addition this issue is specific to HyperOS, which I don't have access to.

**Comment by qmnb12** [comment]
I downgraded the version to 4.0.7 Now everything is going well, I can send messages from contacts and dialer . also by going to + and selecting the contact

**Comment by Inhishonor** [comment]
@qmnb12 I have created a new debug apk (https://github.com/Inhishonor/quik/blob/contact-logging/presentation/build/outputs/apk/debug/QUIK-v4.3.2-debug.apk), can you please install it, reproduce the issue and then email me the logs at (inhishonor at protonmail.com) The reason I am asking for an email, is the apk will log the retrieved contacts. I need this, because I have a feeling the contacts are formed differently on HyperOS than on regular Android. Thanks!

**Comment by EVOTk** [comment]
I also have this problem, unable to start a conversation with a contact. If a conversion is already open with this contact, I have no problem (Honor 70, MagicOS 8.0.0.253, Android 14, QUIK 4.3.2)

Same issue on my 2nd phone : Honor 400 Lite, MagicOS 9.0.0.216, Android 15, QUIK 4.3.2

**Comment by Inhishonor** [comment]
@EVOTk @qmnb12 I have tried some various changes and I might have found a solution. Can you please install this apk, and see if the issue persists: https://github.com/Inhishonor/quik/blob/contact-logging/presentation/build/outputs/apk/debug/QUIK-v4.3.2-debug.apk
If it doesn't work, can you please gather logs and then email them to (inhishonor at protonmail.com). Thanks!

If you want to view my changes they are all present here: https://github.com/octoshrimpy/quik/compare/master...Inhishonor:quik:contact-logging

**Comment by qmnb12** [comment]
I am pasting crashing log....when i try to open h new chat from + and select contact



io.reactivex.exceptions.OnErrorNotImplementedException: Async query cannot be created on current thread. Realm cannot be automatically updated on a thread without a looper.
Caused by: java.lang.IllegalStateException: Async query cannot be created on current thread. Realm cannot be automatically updated on a thread without a looper.
	at dev.octoshrimpy.quik.feature.compose.ComposeViewModel.<init>(ComposeViewModel.kt:202)
	at [[ ↑↑ Inferred subscribe point ↑↑ ]].(:0)
	at [[ ↓↓ Original trace ↓↓ ]].(:0)
	at io.realm.internal.android.AndroidCapabilities.checkCanDeliverNotification(AndroidCapabilities.java:54)
	at io.realm.RealmQuery.findAllAsync(RealmQuery.java:2492)
	at dev.octoshrimpy.quik.repository.ConversationRepositoryImpl.getConversations(ConversationRepositoryImpl.kt:89)
	at dev.octoshrimpy.quik.repository.ConversationRepository$DefaultImpls.getConversations$default(ConversationRepository.kt:30)
	at dev.octoshrimpy.quik.feature.compose.ComposeViewModel$selectedConversation$5.invoke(ComposeViewModel.kt:180)
	at dev.octoshrimpy.quik.feature.compose.ComposeViewModel$selectedConversation$5.invoke(ComposeViewModel.kt:178)
	at dev.octoshrimpy.quik.feature.compose.ComposeViewModel._init_$lambda$7(ComposeViewModel.kt:178)
	at dev.octoshrimpy.quik.feature.compose.ComposeViewModel.$r8$lambda$VlT5b7BFiZK1eyUu8iQPP8XdEe4(Unknown Source:0)
	at dev.octoshrimpy.quik.feature.compose.ComposeViewModel$$ExternalSyntheticLambda47.apply(Unknown Source:2)
	at io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:111)
	at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:101)
	at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:101)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1154)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:652)
	at java.lang.Thread.run(Thread.java:1563)

**Comment by Inhishonor** [comment]
@qmnb12 That issue is separate from the main issue. I will fix it shortly. Can you try to open a conversation from the dialer or contacts app?

**Comment by qmnb12** [comment]
Yes, I tried with contacts and dialer also but the quik app is not opening. By chance it is opening immediately crashing.

**Comment by EVOTk** [comment]
> [@EVOTk](https://github.com/EVOTk) [@qmnb12](https://github.com/qmnb12) I have tried some various changes and I might have found a solution. Can you please install this apk, and see if the issue persists: https://github.com/Inhishonor/quik/blob/contact-logging/presentation/build/outputs/apk/debug/QUIK-v4.3.2-debug.apk If it doesn't work, can you please gather logs and then email them to (inhishonor at protonmail.com). Thanks!
> 
> If you want to view my changes they are all present here: [master...Inhishonor:quik:contact-logging](https://github.com/octoshrimpy/quik/compare/master...Inhishonor:quik:contact-logging)

The problem is still there, but the behavior has changed. Now, after creating a new conversation, the app returns to the home screen.

**Comment by qmnb12** [comment]
> [@EVOTk](https://github.com/EVOTk) [@qmnb12](https://github.com/qmnb12) I have tried some various changes and I might have found a solution. Can you please install this apk, and see if the issue persists: https://github.com/Inhishonor/quik/blob/contact-logging/presentation/build/outputs/apk/debug/QUIK-v4.3.2-debug.apk If it doesn't work, can you please gather logs and then email them to (inhishonor at protonmail.com). Thanks!
> 
> If you want to view my changes they are all present here: [master...Inhishonor:quik:contact-logging](https://github.com/octoshrimpy/quik/compare/master...Inhishonor:quik:contact-logging)

Please give me a new debug apk.
Please Fix The  Crashing Problem...Then i Wil Send You Logs...

**Comment by Inhishonor** [comment]
Alright @EVOTk @qmnb12 Please see the new apk at https://github.com/Inhishonor/quik/blob/contact-logging/presentation/build/outputs/apk/debug/QUIK-v4.3.2-debug.apk. This will log your phone numbers and contacts, so if necessary create a test contact, and then only attempt to open the conversation in that contact. Let's hope this works. 🤞

**Comment by qmnb12** [comment]
> Alright [@EVOTk](https://github.com/EVOTk) [@qmnb12](https://github.com/qmnb12) Please see the new apk at https://github.com/Inhishonor/quik/blob/contact-logging/presentation/build/outputs/apk/debug/QUIK-v4.3.2-debug.apk. This will log your phone numbers and contacts, so if necessary create a test contact, and then only attempt to open the conversation in that contact. Let's hope this works. 🤞

ISSUE 1st From Contact and Dialer Showing This 

![Image](https://github.com/user-attachments/assets/4efdf1b3-a5b7-4dde-85d0-ed6d428f5f52)

Issue = Contact Not Showing And Can't Send Msg.. ( PAST ISSUE WAS NOT SHOWING ANYTHING)

I THINK SEND BUTTON NOT WORKING 

ISSUE 2nd From Direct Message Via App ...

![Image](https://github.com/user-attachments/assets/24508cee-1754-43e1-bf1c-c3791f9a9354)

Issue = All Working but sending button not working..
I am unable to send msg by both

**Comment by Inhishonor** [comment]
@qmnb12 well, that's progress. What happens when you hit the send button? Can you collect logs right after hitting the send button and post them here? Did you give the contact a phone number? Fake or real?

**Comment by qmnb12** [comment]
Send button not responding.. 

Wait for 10 min i am creating logs

**Comment by qmnb12** [comment]
The send button is not responding. Please check your email. I have already sent it. Please react an emoji on this comment if you recieved.

**Comment by Inhishonor** [comment]
Thank you, I will look at them shortly.

**Comment by Inhishonor** [comment]
@qmnb12 @EVOTk Please check the latest apk at https://github.com/Inhishonor/quik/blob/contact-logging/presentation/build/outputs/apk/debug/QUIK-v4.3.2-debug.apk. As usual, if it doesn't work please collect logs with this command: `adb shell logcat --pid=$(pidof -s dev.octoshrimpy.quik)` And it will still log so use a test contact with a validly formatted phone number.

**Comment by qmnb12** [comment]
> **I am unable to send messages to contacts in my contact list** Whenever I try to message a contact, whether I do it directly in the app or through the dialer or contacts, I don't see any option to type or send a message.
> 
> **To Reproduce**
> 
> 1. Go to '+'
> 2. Click on 'Contact'
> 3. See Problem
> 
> **Expected behavior** Only the reload symbol keeps rotating.
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [Redmi 12 5G]
> * OS: [Android 15 , Hyper OS 2.0.2]
> * App Version [e.g. 4.3.2]
> 
> **Screenshots**
> 
> ![Image](https://github.com/user-attachments/assets/d7f4e6e9-5e31-4f10-b132-8c63f4fd3029)
> 
> **Additional context** This happens whenever I try to send a message to any contact from Contacts & Dialer and also when I do it by opening the app.
> 
> Please solve this quickly. If we cannot send messages from the Messages app, then the app becomes useless.
> 
> Please give an update immediately.

Again Same Issue😢

**Comment by Inhishonor** [comment]
What do you mean? Back to infinite loading? What do the logs say?

**Comment by qmnb12** [comment]
Yes infinite loading... I will upload the logs tomorrow

**Comment by Inhishonor** [comment]
@qmnb12 I have uploaded a new apk, please try it and upload logs if it doesn't work. https://github.com/Inhishonor/quik/blob/contact-logging/presentation/build/outputs/apk/debug/QUIK-v4.3.2-debug.apk

**Comment by qmnb12** [comment]
> **I am unable to send messages to contacts in my contact list** Whenever I try to message a contact, whether I do it directly in the app or through the dialer or contacts, I don't see any option to type or send a message.
> 
> **To Reproduce**
> 
> 1. Go to '+'
> 2. Click on 'Contact'
> 3. See Problem
> 
> **Expected behavior** Only the reload symbol keeps rotating.
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [Redmi 12 5G]
> * OS: [Android 15 , Hyper OS 2.0.2]
> * App Version [e.g. 4.3.2]
> 
> **Screenshots**
> 
> ![Image](https://github.com/user-attachments/assets/d7f4e6e9-5e31-4f10-b132-8c63f4fd3029)
> 
> **Additional context** This happens whenever I try to send a message to any contact from Contacts & Dialer and also when I do it by opening the app.
> 
> Please solve this quickly. If we cannot send messages from the Messages app, then the app becomes useless.
> 
> Please give an update immediately.

Bro Same Issue... But 4.0.7 working fine on my device.... I will send you both (4.0.7 and debug) versions logs ok... please give me some time...

**Comment by qmnb12** [comment]
I sended you both logcat.. 4.0.7 ( working fine on my mobile ) and your debug app logcat...react on my comment if you recieved

**Comment by Inhishonor** [comment]
@qmnb12 Can you please try this apk: https://github.com/Inhishonor/quik/actions/runs/20575283823/artifacts/4984450579

**Comment by qmnb12** [comment]
Its a zip file

**Comment by Inhishonor** [comment]
@qmnb12 Yeah, just unzip it. It was built by GitHub Actions as I can't upload an apk right now.

**Comment by qmnb12** [comment]
Yes its working fine...

**Comment by maverick74** [comment]
When sending messages to more than one person, when pressing the "Flip-Switch" it does not slide!

However, the next time I try to create another group message it appears "switched"!

(Android 8.1)

**Comment by Inhishonor** [comment]
@maverick74 @qmnb12 Can you please verify that this latest update works? Including opening a contact from dialer. https://github.com/octoshrimpy/quik/actions/runs/20601460068/artifacts/4992639387
This is the final code change, that is present in the pull request.

@maverick74 Does this fix the group message issue?

**Comment by qmnb12** [comment]
> [@qmnb12](https://github.com/qmnb12) Can you please try this apk: https://github.com/Inhishonor/quik/actions/runs/20575283823/artifacts/4984450579

This is working fine in both ( from + and from contact and dialer 

> [@maverick74](https://github.com/maverick74) [@qmnb12](https://github.com/qmnb12) Can you please verify that this latest update works? Including opening a contact from dialer. https://github.com/octoshrimpy/quik/actions/runs/20601460068/artifacts/4992639387 This is the final code change, that is present in the pull request.
> 
> [@maverick74](https://github.com/maverick74) Does this fix the group message issue?

But in this app is crashing in both method contact and Dialer and from +

**Comment by qmnb12** [comment]
Crash logs from +

io.reactivex.exceptions.OnErrorNotImplementedException: Object is no longer valid to operate on. Was it deleted by another thread?
Caused by: java.lang.IllegalStateException: Object is no longer valid to operate on. Was it deleted by another thread?
	at dev.octoshrimpy.quik.feature.compose.ComposeViewModel.<init>(ComposeViewModel.kt:200)
	at [[ ↑↑ Inferred subscribe point ↑↑ ]].(:0)
	at [[ ↓↓ Original trace ↓↓ ]].(:0)
	at io.realm.internal.UncheckedRow.nativeGetObjectKey(Native Method)
	at io.realm.internal.UncheckedRow.getObjectKey(UncheckedRow.java:131)
	at io.realm.dev_octoshrimpy_quik_model_ContactRealmProxy.hashCode(dev_octoshrimpy_quik_model_ContactRealmProxy.java:906)
	at java.util.HashMap.hash(HashMap.java:337)
	at java.util.HashMap.getNode(HashMap.java:575)
	at java.util.HashMap.get(HashMap.java:563)
	at io.realm.dev_octoshrimpy_quik_model_RecipientRealmProxy.update(dev_octoshrimpy_quik_model_RecipientRealmProxy.java:645)
	at io.realm.dev_octoshrimpy_quik_model_RecipientRealmProxy.copyOrUpdate(dev_octoshrimpy_quik_model_RecipientRealmProxy.java:400)
	at io.realm.dev_octoshrimpy_quik_model_ConversationRealmProxy.copy(dev_octoshrimpy_quik_model_ConversationRealmProxy.java:842)
	at io.realm.dev_octoshrimpy_quik_model_ConversationRealmProxy.copyOrUpdate(dev_octoshrimpy_quik_model_ConversationRealmProxy.java:799)
	at io.realm.DefaultRealmModuleMediator.copyOrUpdate(DefaultRealmModuleMediator.java:319)
	at io.realm.Realm.copyOrUpdate(Realm.java:1844)
	at io.realm.Realm.copyToRealmOrUpdate(Realm.java:1228)
	at dev.octoshrimpy.quik.repository.ConversationRepositoryImpl.createEmptyConversation$lambda$79$lambda$78(ConversationRepositoryImpl.kt:567)
	at dev.octoshrimpy.quik.repository.ConversationRepositoryImpl.$r8$lambda$ICOjLTvm5YOR_ID7De8Fh-NahyA(Unknown Source:0)
	at dev.octoshrimpy.quik.repository.ConversationRepositoryImpl$$ExternalSyntheticLambda11.execute(Unknown Source:2)
	at io.realm.Realm.executeTransaction(Realm.java:1633)
	at dev.octoshrimpy.quik.repository.ConversationRepositoryImpl.createEmptyConversation(ConversationRepositoryImpl.kt:567)
	at dev.octoshrimpy.quik.repository.ConversationRepositoryImpl.createConversation(ConversationRepositoryImpl.kt:344)
	at dev.octoshrimpy.quik.repository.ConversationRepositoryImpl.getOrCreateConversation(ConversationRepositoryImpl.kt:351)
	at dev.octoshrimpy.quik.repository.ConversationRepository$DefaultImpls.getOrCreateConversation$default(ConversationRepository.kt:72)
	at dev.octoshrimpy.quik.feature.compose.ComposeViewModel$selectedConversation$4.invoke(ComposeViewModel.kt:175)
	at dev.octoshrimpy.quik.feature.compose.ComposeViewModel$selectedConversation$4.invoke(ComposeViewModel.kt:175)
	at dev.octoshrimpy.quik.feature.compose.ComposeViewModel._init_$lambda$6(ComposeViewModel.kt:175)
	at dev.octoshrimpy.quik.feature.compose.ComposeViewModel.$r8$lambda$UtCjlpR8lcGjukN7UTYpxkfX9xQ(Unknown Source:0)
	at dev.octoshrimpy.quik.feature.compose.ComposeViewModel$$ExternalSyntheticLambda47.accept(Unknown Source:2)
	at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:93)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1154)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:652)
	at java.lang.Thread.run(Thread.java:1563)

**Comment by qmnb12** [comment]
From Contacts And Dialer 

io.reactivex.exceptions.OnErrorNotImplementedException: Only valid managed objects can be copied from Realm.
Caused by: java.lang.IllegalArgumentException: Only valid managed objects can be copied from Realm.
	at dev.octoshrimpy.quik.feature.compose.ComposeViewModel.<init>(ComposeViewModel.kt:200)
	at [[ ↑↑ Inferred subscribe point ↑↑ ]].(:0)
	at [[ ↓↓ Original trace ↓↓ ]].(:0)
	at io.realm.Realm.checkValidObjectForDetach(Realm.java:1893)
	at io.realm.Realm.copyFromRealm(Realm.java:1551)
	at io.realm.Realm.copyFromRealm(Realm.java:1524)
	at dev.octoshrimpy.quik.repository.ConversationRepositoryImpl.createEmptyConversation(ConversationRepositoryImpl.kt:568)
	at dev.octoshrimpy.quik.repository.ConversationRepositoryImpl.createConversation(ConversationRepositoryImpl.kt:344)
	at dev.octoshrimpy.quik.repository.ConversationRepositoryImpl.getOrCreateConversation(ConversationRepositoryImpl.kt:351)
	at dev.octoshrimpy.quik.repository.ConversationRepository$DefaultImpls.getOrCreateConversation$default(ConversationRepository.kt:72)
	at dev.octoshrimpy.quik.feature.compose.ComposeViewModel$selectedConversation$4.invoke(ComposeViewModel.kt:175)
	at dev.octoshrimpy.quik.feature.compose.ComposeViewModel$selectedConversation$4.invoke(ComposeViewModel.kt:175)
	at dev.octoshrimpy.quik.feature.compose.ComposeViewModel._init_$lambda$6(ComposeViewModel.kt:175)
	at dev.octoshrimpy.quik.feature.compose.ComposeViewModel.$r8$lambda$UtCjlpR8lcGjukN7UTYpxkfX9xQ(Unknown Source:0)
	at dev.octoshrimpy.quik.feature.compose.ComposeViewModel$$ExternalSyntheticLambda47.accept(Unknown Source:2)
	at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:93)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1154)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:652)
	at java.lang.Thread.run(Thread.java:1563)

**Comment by maverick74** [comment]
@Inhishonor using the debug version you sent: i confirm mostly the same experience as @qmnb12 with a few differences!

I'm not getting crashes when I try to send a message from the dialer's contact list and when adding multiple contacts from within the app it doesn't "always" crash! Just happens most of the time... 

When it doesn't happen, I'm afraid the flip-switch still does not work... 

(edit: keep in mind this is Android 8.1. It's almost dead! If it doesn't happen in newer versions I don't know if it's worth the trouble)

**Comment by Inhishonor** [comment]
@maverick74 @qmnb12 New apk uploaded, that I am hoping will fix this issue. @qmnb12 Are you having the issue with the group chat switch?

@maverick74 I think that the group chat switch not working is a different problem than this one, so I will have to take another look at it later.

**Comment by qmnb12** [comment]
> [@maverick74](https://github.com/maverick74) [@qmnb12](https://github.com/qmnb12) New apk uploaded, that I am hoping will fix this issue. [@qmnb12](https://github.com/qmnb12) Are you having the issue with the group chat switch?
> 
> [@maverick74](https://github.com/maverick74) I think that the group chat switch not working is a different problem than this one, so I will have to take another look at it later.

Where is the apk..?

**Comment by Inhishonor** [comment]
Sorry forgot to add it: https://github.com/octoshrimpy/quik/actions/runs/20610114255/artifacts/4995313041

**Comment by qmnb12** [comment]
> [@maverick74](https://github.com/maverick74) [@qmnb12](https://github.com/qmnb12) New apk uploaded, that I am hoping will fix this issue. [@qmnb12](https://github.com/qmnb12) Are you having the issue with the group chat switch?
> 
> [@maverick74](https://github.com/maverick74) I think that the group chat switch not working is a different problem than this one, so I will have to take another look at it later.

Group chat switch is working fine. Almost all the issues are fixed in the last APK file.Now I can send messages from Contacts and Dialer and also from within the app.Now currently there is no crash issue. When will the stable update come in releases? If it takes time, I will keep this debug apk in my phone for testing.

Thanks for your time and efforts.

**Comment by Inhishonor** [comment]
Great! I am not sure how long it will be before release, I don't handle that aspect, but hopefully soon. Thank you for your help with debugging.

**Comment by maverick74** [comment]
> [@maverick74](https://github.com/maverick74) I think that the group chat switch not working is a different problem than this one, so I will have to take another look at it later.

Yeah! The switch issue remains here! Everything else seems to be fixed! It's Just the switch problem that remains!

**Comment by maverick74** [comment]
> > [@maverick74](https://github.com/maverick74) I think that the group chat switch not working is a different problem than this one, so I will have to take another look at it later.

> @Inhishonor is there another bug report open for _the switch problem_ or do you want me to create one?

Never mind my stupid question!!!!  #668
